"""initial schema

Revision ID: b281bc762a8d
Revises:
Create Date: 2026-08-02 15:48:25.531762
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b281bc762a8d"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agents",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=64), nullable=False),
        sa.Column("adapter_id", sa.String(length=64), nullable=True),
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["adapter_id"],
            ["adapters.id"],
            name="fk_agents_adapter_id_adapters",
            ondelete="RESTRICT",
            use_alter=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agents")),
    )
    op.create_index(
        op.f("ix_agents_adapter_id"), "agents", ["adapter_id"], unique=False
    )
    op.create_table(
        "graders",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("family", sa.String(length=64), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=64), nullable=False),
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_graders")),
    )
    op.create_table(
        "projects",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=64), nullable=False),
        sa.Column(
            "settings",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_projects")),
    )
    op.create_table(
        "adapters",
        sa.Column("agent_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=64), nullable=False),
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
            name=op.f("fk_adapters_agent_id_agents"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_adapters")),
    )
    op.create_index(op.f("ix_adapters_agent_id"), "adapters", ["agent_id"], unique=True)
    op.create_table(
        "agent_versions",
        sa.Column("agent_id", sa.String(length=64), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=64), nullable=False),
        sa.Column("label", sa.String(length=255), nullable=False),
        sa.Column("release_notes", sa.Text(), nullable=False),
        sa.Column("predecessor_version_id", sa.String(length=64), nullable=True),
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
            name=op.f("fk_agent_versions_agent_id_agents"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["predecessor_version_id"],
            ["agent_versions.id"],
            name=op.f("fk_agent_versions_predecessor_version_id_agent_versions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_versions")),
        sa.UniqueConstraint(
            "agent_id",
            "version_number",
            name="uq_agent_versions_agent_id_version_number",
        ),
    )
    op.create_index(
        op.f("ix_agent_versions_agent_id"), "agent_versions", ["agent_id"], unique=False
    )
    op.create_table(
        "audit_logs",
        sa.Column("actor_id", sa.String(length=64), nullable=False),
        sa.Column("action", sa.String(length=128), nullable=False),
        sa.Column("project_id", sa.String(length=64), nullable=True),
        sa.Column("subject_type", sa.String(length=128), nullable=True),
        sa.Column("subject_id", sa.String(length=64), nullable=True),
        sa.Column(
            "detail",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_audit_logs_project_id_projects"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    op.create_index(
        op.f("ix_audit_logs_actor_id"), "audit_logs", ["actor_id"], unique=False
    )
    op.create_index(
        op.f("ix_audit_logs_project_id"), "audit_logs", ["project_id"], unique=False
    )
    op.create_table(
        "cases",
        sa.Column("project_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=64), nullable=False),
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_cases_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cases")),
        sa.UniqueConstraint("project_id", "name", name="uq_cases_project_id_name"),
    )
    op.create_index(op.f("ix_cases_project_id"), "cases", ["project_id"], unique=False)
    op.create_table(
        "grader_versions",
        sa.Column("grader_id", sa.String(length=64), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=64), nullable=False),
        sa.Column("label", sa.String(length=255), nullable=False),
        sa.Column("specification", sa.Text(), nullable=False),
        sa.Column("predecessor_version_id", sa.String(length=64), nullable=True),
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["grader_id"],
            ["graders.id"],
            name=op.f("fk_grader_versions_grader_id_graders"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["predecessor_version_id"],
            ["grader_versions.id"],
            name=op.f("fk_grader_versions_predecessor_version_id_grader_versions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_grader_versions")),
        sa.UniqueConstraint(
            "grader_id",
            "version_number",
            name="uq_grader_versions_grader_id_version_number",
        ),
    )
    op.create_index(
        op.f("ix_grader_versions_grader_id"),
        "grader_versions",
        ["grader_id"],
        unique=False,
    )
    op.create_table(
        "suites",
        sa.Column("project_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=64), nullable=False),
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_suites_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_suites")),
        sa.UniqueConstraint("project_id", "name", name="uq_suites_project_id_name"),
    )
    op.create_index(
        op.f("ix_suites_project_id"), "suites", ["project_id"], unique=False
    )
    op.create_table(
        "adapter_versions",
        sa.Column("adapter_id", sa.String(length=64), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=64), nullable=False),
        sa.Column("label", sa.String(length=255), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("predecessor_version_id", sa.String(length=64), nullable=True),
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["adapter_id"],
            ["adapters.id"],
            name=op.f("fk_adapter_versions_adapter_id_adapters"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["predecessor_version_id"],
            ["adapter_versions.id"],
            name=op.f("fk_adapter_versions_predecessor_version_id_adapter_versions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_adapter_versions")),
        sa.UniqueConstraint(
            "adapter_id",
            "version_number",
            name="uq_adapter_versions_adapter_id_version_number",
        ),
    )
    op.create_index(
        op.f("ix_adapter_versions_adapter_id"),
        "adapter_versions",
        ["adapter_id"],
        unique=False,
    )
    op.create_table(
        "prompts",
        sa.Column("case_id", sa.String(length=64), nullable=False),
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["cases.id"],
            name=op.f("fk_prompts_case_id_cases"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_prompts")),
    )
    op.create_index(op.f("ix_prompts_case_id"), "prompts", ["case_id"], unique=True)
    op.create_table(
        "suite_versions",
        sa.Column("suite_id", sa.String(length=64), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=64), nullable=False),
        sa.Column("predecessor_version_id", sa.String(length=64), nullable=True),
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["predecessor_version_id"],
            ["suite_versions.id"],
            name=op.f("fk_suite_versions_predecessor_version_id_suite_versions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["suite_id"],
            ["suites.id"],
            name=op.f("fk_suite_versions_suite_id_suites"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_suite_versions")),
        sa.UniqueConstraint(
            "suite_id",
            "version_number",
            name="uq_suite_versions_suite_id_version_number",
        ),
    )
    op.create_index(
        op.f("ix_suite_versions_suite_id"), "suite_versions", ["suite_id"], unique=False
    )
    op.create_table(
        "prompt_versions",
        sa.Column("prompt_id", sa.String(length=64), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=64), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("predecessor_version_id", sa.String(length=64), nullable=True),
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["predecessor_version_id"],
            ["prompt_versions.id"],
            name=op.f("fk_prompt_versions_predecessor_version_id_prompt_versions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["prompt_id"],
            ["prompts.id"],
            name=op.f("fk_prompt_versions_prompt_id_prompts"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_prompt_versions")),
        sa.UniqueConstraint(
            "prompt_id",
            "version_number",
            name="uq_prompt_versions_prompt_id_version_number",
        ),
    )
    op.create_index(
        op.f("ix_prompt_versions_prompt_id"),
        "prompt_versions",
        ["prompt_id"],
        unique=False,
    )
    op.create_table(
        "case_versions",
        sa.Column("case_id", sa.String(length=64), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=64), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("repository_url", sa.String(length=2048), nullable=False),
        sa.Column("commit_sha", sa.String(length=128), nullable=False),
        sa.Column("subdirectory", sa.String(length=1024), nullable=True),
        sa.Column(
            "expected_checks",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column("prompt_version_id", sa.String(length=64), nullable=False),
        sa.Column("predecessor_version_id", sa.String(length=64), nullable=True),
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["cases.id"],
            name=op.f("fk_case_versions_case_id_cases"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["predecessor_version_id"],
            ["case_versions.id"],
            name=op.f("fk_case_versions_predecessor_version_id_case_versions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["prompt_version_id"],
            ["prompt_versions.id"],
            name=op.f("fk_case_versions_prompt_version_id_prompt_versions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_case_versions")),
        sa.UniqueConstraint(
            "case_id", "version_number", name="uq_case_versions_case_id_version_number"
        ),
    )
    op.create_index(
        op.f("ix_case_versions_case_id"), "case_versions", ["case_id"], unique=False
    )
    op.create_index(
        op.f("ix_case_versions_prompt_version_id"),
        "case_versions",
        ["prompt_version_id"],
        unique=False,
    )
    op.create_table(
        "case_grader_declarations",
        sa.Column("case_version_id", sa.String(length=64), nullable=False),
        sa.Column("grader_id", sa.String(length=64), nullable=False),
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["case_version_id"],
            ["case_versions.id"],
            name=op.f("fk_case_grader_declarations_case_version_id_case_versions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["grader_id"],
            ["graders.id"],
            name=op.f("fk_case_grader_declarations_grader_id_graders"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_case_grader_declarations")),
        sa.UniqueConstraint(
            "case_version_id",
            "grader_id",
            name="uq_case_grader_declarations_case_version_id_grader_id",
        ),
    )
    op.create_index(
        op.f("ix_case_grader_declarations_case_version_id"),
        "case_grader_declarations",
        ["case_version_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_case_grader_declarations_grader_id"),
        "case_grader_declarations",
        ["grader_id"],
        unique=False,
    )
    op.create_table(
        "runs",
        sa.Column("lock_version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("status", sa.String(length=64), nullable=False),
        sa.Column("project_id", sa.String(length=64), nullable=False),
        sa.Column("case_version_id", sa.String(length=64), nullable=False),
        sa.Column("prompt_version_id", sa.String(length=64), nullable=False),
        sa.Column("agent_version_id", sa.String(length=64), nullable=False),
        sa.Column("adapter_version_id", sa.String(length=64), nullable=False),
        sa.Column("platform_version_id", sa.String(length=64), nullable=False),
        sa.Column("suite_version_id", sa.String(length=64), nullable=True),
        sa.Column(
            "grader_version_ids",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.Column("cancellation_reason", sa.Text(), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("wall_clock_ms", sa.Integer(), nullable=True),
        sa.Column("compute_ms", sa.Integer(), nullable=True),
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["adapter_version_id"],
            ["adapter_versions.id"],
            name=op.f("fk_runs_adapter_version_id_adapter_versions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["agent_version_id"],
            ["agent_versions.id"],
            name=op.f("fk_runs_agent_version_id_agent_versions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["case_version_id"],
            ["case_versions.id"],
            name=op.f("fk_runs_case_version_id_case_versions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_runs_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["prompt_version_id"],
            ["prompt_versions.id"],
            name=op.f("fk_runs_prompt_version_id_prompt_versions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["suite_version_id"],
            ["suite_versions.id"],
            name=op.f("fk_runs_suite_version_id_suite_versions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_runs")),
    )
    op.create_index(
        op.f("ix_runs_adapter_version_id"), "runs", ["adapter_version_id"], unique=False
    )
    op.create_index(
        op.f("ix_runs_agent_version_id"), "runs", ["agent_version_id"], unique=False
    )
    op.create_index(
        op.f("ix_runs_case_version_id"), "runs", ["case_version_id"], unique=False
    )
    op.create_index(op.f("ix_runs_project_id"), "runs", ["project_id"], unique=False)
    op.create_index(
        op.f("ix_runs_prompt_version_id"), "runs", ["prompt_version_id"], unique=False
    )
    op.create_index(
        op.f("ix_runs_suite_version_id"), "runs", ["suite_version_id"], unique=False
    )
    op.create_table(
        "suite_compositions",
        sa.Column("suite_version_id", sa.String(length=64), nullable=False),
        sa.Column("case_version_id", sa.String(length=64), nullable=False),
        sa.Column("case_project_id", sa.String(length=64), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["case_project_id"],
            ["projects.id"],
            name=op.f("fk_suite_compositions_case_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["case_version_id"],
            ["case_versions.id"],
            name=op.f("fk_suite_compositions_case_version_id_case_versions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["suite_version_id"],
            ["suite_versions.id"],
            name=op.f("fk_suite_compositions_suite_version_id_suite_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_suite_compositions")),
        sa.UniqueConstraint(
            "suite_version_id",
            "case_version_id",
            name="uq_suite_compositions_suite_version_id_case_version_id",
        ),
        sa.UniqueConstraint(
            "suite_version_id",
            "position",
            name="uq_suite_compositions_suite_version_id_position",
        ),
    )
    op.create_index(
        op.f("ix_suite_compositions_case_version_id"),
        "suite_compositions",
        ["case_version_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_suite_compositions_suite_version_id"),
        "suite_compositions",
        ["suite_version_id"],
        unique=False,
    )
    op.create_table(
        "artifacts",
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column("storage_key", sa.String(length=2048), nullable=False),
        sa.Column("content_type", sa.String(length=255), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("checksum", sa.String(length=128), nullable=False),
        sa.Column("produced_by_grader_version_id", sa.String(length=64), nullable=True),
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["produced_by_grader_version_id"],
            ["grader_versions.id"],
            name=op.f("fk_artifacts_produced_by_grader_version_id_grader_versions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
            name=op.f("fk_artifacts_run_id_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_artifacts")),
    )
    op.create_index(op.f("ix_artifacts_run_id"), "artifacts", ["run_id"], unique=False)
    op.create_table(
        "execution_events",
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column(
            "action_payload",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "event_metadata",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column(
            "artifact_ids",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
            name=op.f("fk_execution_events_run_id_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_execution_events")),
        sa.UniqueConstraint(
            "run_id", "sequence", name="uq_execution_events_run_id_sequence"
        ),
    )
    op.create_index(
        op.f("ix_execution_events_run_id"), "execution_events", ["run_id"], unique=False
    )
    op.create_table(
        "scores",
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("grader_id", sa.String(length=64), nullable=False),
        sa.Column("grader_version_id", sa.String(length=64), nullable=False),
        sa.Column("numeric_value", sa.Float(), nullable=True),
        sa.Column("categorical_value", sa.String(length=255), nullable=True),
        sa.Column("passed", sa.Boolean(), nullable=True),
        sa.Column(
            "detail",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column("explanation_artifact_id", sa.String(length=64), nullable=True),
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["explanation_artifact_id"],
            ["artifacts.id"],
            name=op.f("fk_scores_explanation_artifact_id_artifacts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["grader_id"],
            ["graders.id"],
            name=op.f("fk_scores_grader_id_graders"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["grader_version_id"],
            ["grader_versions.id"],
            name=op.f("fk_scores_grader_version_id_grader_versions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
            name=op.f("fk_scores_run_id_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scores")),
        sa.UniqueConstraint(
            "run_id", "grader_version_id", name="uq_scores_run_id_grader_version_id"
        ),
    )
    op.create_index(op.f("ix_scores_grader_id"), "scores", ["grader_id"], unique=False)
    op.create_index(
        op.f("ix_scores_grader_version_id"),
        "scores",
        ["grader_version_id"],
        unique=False,
    )
    op.create_index(op.f("ix_scores_run_id"), "scores", ["run_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_scores_run_id"), table_name="scores")
    op.drop_index(op.f("ix_scores_grader_version_id"), table_name="scores")
    op.drop_index(op.f("ix_scores_grader_id"), table_name="scores")
    op.drop_table("scores")
    op.drop_index(op.f("ix_execution_events_run_id"), table_name="execution_events")
    op.drop_table("execution_events")
    op.drop_index(op.f("ix_artifacts_run_id"), table_name="artifacts")
    op.drop_table("artifacts")
    op.drop_index(
        op.f("ix_suite_compositions_suite_version_id"), table_name="suite_compositions"
    )
    op.drop_index(
        op.f("ix_suite_compositions_case_version_id"), table_name="suite_compositions"
    )
    op.drop_table("suite_compositions")
    op.drop_index(op.f("ix_runs_suite_version_id"), table_name="runs")
    op.drop_index(op.f("ix_runs_prompt_version_id"), table_name="runs")
    op.drop_index(op.f("ix_runs_project_id"), table_name="runs")
    op.drop_index(op.f("ix_runs_case_version_id"), table_name="runs")
    op.drop_index(op.f("ix_runs_agent_version_id"), table_name="runs")
    op.drop_index(op.f("ix_runs_adapter_version_id"), table_name="runs")
    op.drop_table("runs")
    op.drop_index(
        op.f("ix_case_grader_declarations_grader_id"),
        table_name="case_grader_declarations",
    )
    op.drop_index(
        op.f("ix_case_grader_declarations_case_version_id"),
        table_name="case_grader_declarations",
    )
    op.drop_table("case_grader_declarations")
    op.drop_index(
        op.f("ix_case_versions_prompt_version_id"), table_name="case_versions"
    )
    op.drop_index(op.f("ix_case_versions_case_id"), table_name="case_versions")
    op.drop_table("case_versions")
    op.drop_index(op.f("ix_prompt_versions_prompt_id"), table_name="prompt_versions")
    op.drop_table("prompt_versions")
    op.drop_index(op.f("ix_suite_versions_suite_id"), table_name="suite_versions")
    op.drop_table("suite_versions")
    op.drop_index(op.f("ix_prompts_case_id"), table_name="prompts")
    op.drop_table("prompts")
    op.drop_index(op.f("ix_adapter_versions_adapter_id"), table_name="adapter_versions")
    op.drop_table("adapter_versions")
    op.drop_index(op.f("ix_suites_project_id"), table_name="suites")
    op.drop_table("suites")
    op.drop_index(op.f("ix_grader_versions_grader_id"), table_name="grader_versions")
    op.drop_table("grader_versions")
    op.drop_index(op.f("ix_cases_project_id"), table_name="cases")
    op.drop_table("cases")
    op.drop_index(op.f("ix_audit_logs_project_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_actor_id"), table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_agent_versions_agent_id"), table_name="agent_versions")
    op.drop_table("agent_versions")
    op.drop_index(op.f("ix_adapters_agent_id"), table_name="adapters")
    op.drop_table("adapters")
    op.drop_table("projects")
    op.drop_table("graders")
    op.drop_index(op.f("ix_agents_adapter_id"), table_name="agents")
    op.drop_table("agents")
    # ### end Alembic commands ###
